### ISSUE TITLE
Incompatibility with latest pry

### ISSUE THREAD

**Issue by pjg** [cldwalker/hirb#81]
When using latest `hirb` with latest `pry` (version `0.10.0`) and latest Rails (4.1.1) I see this error almost all the time (when doing anything in Rails console):

```
(pry) output error: #<NoMethodError: undefined method `pager' for nil:NilClass>
```

I'm also using hirb initializer from #46.

I think it's because pry cannot agree with hirb on how to use paging... but that's just guessing.

**Comment by MehdiK** [comment]
That was really annoying and @emptyflask's solution worked like a charm. Thanks a lot.

**Comment by AnwarShah** [comment]
The workaround provided by @emptyflask works flawlessly. Big Thanks!

**Comment by sobinsunny** [comment]
@emptyflask  awesome dude.It's working
