### ISSUE TITLE
More examples?

### ISSUE THREAD

**Issue by thams** [cldwalker/hirb#85]
Looking for examples on how to create (and use) custom views. 

Like: How to make some activerecord models show specific columns by default, but then to optionally see a different set of columns. (without manually putting the :fields argument in and enumerating them)

**Comment by cldwalker** [comment]
Thanks for reporting your issue! This is [one of my 15 active issues](https://gh-active-issues.herokuapp.com/#cldwalker/hirb#85). Use that link to check how soon your issue will be answered. Don't forget to check your issue against this project's CONTRIBUTING.md. Cheers.

**Comment by cldwalker** [comment]
The [readme](https://github.com/cldwalker/hirb#view-tutorials) links to [such a tutorial](http://tagaholic.me/hirb/doc/classes/Hirb/View.html). While hirb uses [AutoTable](https://github.com/cldwalker/hirb/blob/master/lib/hirb/helpers/auto_table.rb) for AR classes, you could define and use your own view/helper class that hardcodes the specific default columns you want. If you end up reusing ObjectTable class like AutoTable does, then you should set the :fields option with the default columns you want.
