### ISSUE TITLE
Hirb::Util.detect_terminal_size should prefer tputs/stty over environment variables

### ISSUE THREAD

**Issue by afn** [cldwalker/hirb#89]
If the window is resized in the middle of a session, and the shell (e.g. zsh) has set `COLUMNS` and `LINES`, then calling `Hirb::View.resize` doesn't correctly detect the new terminal size, even though `stty size` does return the new size.

`Hirb::Util.detect_terminal_size` should only fall back on `COLUMNS` and `LINES` if it cannot detect the size using `tputs` or `stty`.

**Comment by cldwalker** [comment]
Thanks for reporting your issue! This is [one of my 15 active issues](https://gh-active-issues.herokuapp.com/#cldwalker/hirb#89). Use that link to check how soon your issue will be answered. Don't forget to check your issue against this project's CONTRIBUTING.md. Cheers.

**Comment by cldwalker** [comment]
hirb expects ENV vars to be set explicitly by the user and is a way to override any automated way of setting size e.g. stty. I'm using zsh on OSX and my `$COLUMNS` and `$LINES` aren't being set automatically. I'd recommend reconfiguring zsh to not auto-set those vars when you resize. Alternatively, just nil out those ENVs: `ENV['COLUMNS'] = ENV['LINES'] = nil` after a resize
