### ISSUE TITLE
Question: How should I pronounce "hirb"?

### ISSUE THREAD

**Issue by sutara79** [cldwalker/hirb#91]
- high interactive ruby
- high irb
- handy irb
- helpful irb

I'm sorry for asking a worthless question.

**Comment by cldwalker** [comment]
Thanks for reporting your issue! This is [one of my 3 active issues](https://gh-active-issues.herokuapp.com/#cldwalker/hirb#91). Use that link to check how soon your issue will be answered. Don't forget to check your issue against this project's CONTRIBUTING.md. Cheers.

**Comment by cldwalker** [comment]
It's pronounced herb. As for what it stands for, nothing in particular. Though it would be a funny name. Cheers!

**Comment by sutara79** [comment]
Thank you.
