### ISSUE TITLE
Vertical Table for ActiveResource?

### ISSUE THREAD

**Issue by jessenovu** [cldwalker/hirb#95]
I prefer to use Hirb to output ActiveRecord rows vertically. This is a lot like MySQL's `\G` vertical formatter: http://forums.mysql.com/read.php?108,231614

To make this happen, I use the following `hirb.conf`:

``` :output:
  "ActiveRecord::Base":
    :class: auto_table
    :ancestor: true
    :options:
      :vertical: true
```

Is there a way to get the same vertical output for my ActiveResource objects? I tried substituting "ActiveRecord::Base" for "ActiveResource::Base", but the output is less than inspiring.

**Comment by cldwalker** [comment]
Thanks for reporting your issue! This is [one of my 8 active issues](https://gh-active-issues.herokuapp.com/#cldwalker/hirb#95). Use that link to check how soon your issue will be answered. Don't forget to check your issue against this project's CONTRIBUTING.md. Cheers.

**Comment by cldwalker** [comment]
Hi. Hirb doesn't ship with ActiveResource support. You can write your [own dynamic view](http://tagaholic.me/hirb/doc/classes/Hirb/DynamicView.html) using [activerecord as an example](https://github.com/cldwalker/hirb/blob/264f72c7c0f0966001e802414a5b0641036c7860/lib/hirb/views/rails.rb). Closing but feel free to ping here if you run into issues building it
